---
- hosts: all
  become: yes
  tasks:
    - apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates

- hosts: all
  become: yes
  roles:
    - geerlingguy.docker, 1.2.0
  tasks:
    - user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
